# Generated by Django 4.0 on 2024-03-18 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_jobpost_type_alter_jobpost_description'),
        ('uploadapp', '0002_uploadfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='files')),
                ('description', models.CharField(max_length=100)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jobpost')),
            ],
        ),
        migrations.DeleteModel(
            name='UploadFile',
        ),
    ]
